version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8000:8000
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
